// all NFL teams and their titles
export const teams = {'DAL': {'name': 'Dallas Cowboys',
                       'logo': 'dal-2026',
                       'division': 'NFC East'},
              'PHI': {'name': 'Philadelphia Eagles',
                      'logo': 'phi-2026',
                      'division': 'NFC East'},
              'KAN': {'name': 'Kansas City Chiefs',
                      'logo': 'kan-2026',
                      'division': 'AFC West'},
              'LAC': {'name': 'Los Angeles Chargers',
                      'logo': 'sdg-2026',
                      'division': 'AFC West'},
              'TAM': {'name': 'Tampa Bay Buccaneers',
                      'logo': 'tam-2026',
                      'division': 'NFC South'},
              'ATL': {'name': 'Atlanta Falcons',
                      'logo': 'atl-2026',
                      'division': 'NFC South'},
              'CIN': {'name': 'Cincinnati Bengals',
                      'logo': 'cin-2026',
                      'division': 'AFC North'},
              'CLE': {'name': 'Cleveland Browns',
                      'logo': 'cle-2026',
                      'division': 'AFC North'},
              'MIA': {'name': 'Miami Dolphins',
                      'logo': 'mia-2026',
                      'division': 'AFC East'},
              'CLT': {'name': 'Indianapolis Colts',
                      'logo': 'clt-2026',
                      'division': 'AFC South'},
              'CAR': {'name': 'Carolina Panthers',
                      'logo': 'car-2026',
                      'division': 'NFC South'},
              'JAX': {'name': 'Jacksonville Jaguars',
                      'logo': 'jax-2026',
                      'division': 'AFC South'},
              'RAI': {'name': 'Las Vegas Raiders',
                      'logo': 'rai-2026',
                      'division': 'AFC West'},
              'NE': {'name': 'New England Patriots',
                      'logo': 'nwe-2026',
                      'division': 'AFC East'},
              'CRD': {'name': 'Arizona Cardinals',
                      'logo': 'crd-2026',
                      'division': 'NFC West'},
              'NOR': {'name': 'New Orleans Saints',
                      'logo': 'nor-2026',
                      'division': 'NFC South'},
              'PIT': {'name': 'Pittsburgh Steelers',
                      'logo': 'pit-2026',
                      'division': 'AFC North'},
              'NYJ': {'name': 'New York Jets',
                      'logo': 'nyj-2026',
                      'division': 'AFC East'},
              'NYG': {'name': 'New York Giants',
                      'logo': 'nyg-2026',
                      'division': 'NFC East'},
              'WAS': {'name': 'Washington Commanders',
                      'logo': 'was-2026',
                      'division': 'NFC East'},
              'TEN': {'name': 'Tennessee Titans',
                      'logo': 'oti-2026',
                      'division': 'AFC South'},
              'DEN': {'name': 'Denver Broncos',
                      'logo': 'den-2026',
                      'division': 'AFC West'},
              'SFO': {'name': 'San Francisco 49ers',
                      'logo': 'sfo-2026',
                      'division': 'NFC West'},
              'SEA': {'name': 'Seattle Seahawks',
                      'logo': 'sea-2026',
                      'division': 'NFC West'},
              'DET': {'name': 'Detroit Lions',
                      'logo': 'det-2026',
                      'division': 'NFC North'},
              'GNB': {'name': 'Green Bay Packers',
                      'logo': 'gnb-2026',
                      'division': 'NFC North'},
              'HTX': {'name': 'Houston Texans',
                      'logo': 'htx-2026',
                      'division': 'AFC South'},
              'RAM': {'name': 'Los Angeles Rams',
                      'logo': 'ram-2026',
                      'division': 'NFC West'},
              'RAV': {'name': 'Baltimore Ravens',
                      'logo': 'rav-2026',
                      'division': 'AFC North'},
              'BUF': {'name': 'Buffalo Bills',
                      'logo': 'buf-2026',
                      'division': 'AFC East'},
              'MIN': {'name': 'Minnesota Vikings',
                      'logo': 'min-2026',
                      'division': 'NFC North'},
              'CHI': {'name': 'Chicago Bears',
                      'logo': 'chi-2026',
                      'division': 'NFC North'}};

// all weeks and matchup date/times from each
export const weekLengthInfo = [{'start': '2026-08-01',
                                'end': '2026-09-01'},

                               {'start': '2026-09-01',
                                'end': '2026-09-15'}, 

                               {'start': '2026-09-15',
                                'end': '2026-09-22'},

                               {'start': '2026-09-22',
                                'end': '2026-09-29'},

                               {'start': '2026-09-29',
                                'end': '2026-10-06'},

                               {'start': '2026-10-06',
                                'end': '2026-10-13'},

                               {'start': '2026-10-13',
                                'end': '2026-10-20'},

                                {'start': '2026-10-20',
                                'end': '2026-10-27'},

                                {'start': '2025-10-21',
                                'end': '2025-10-28'},

                                {'start': '2025-10-28',
                                'end': '2025-11-04'},

                                {'start': '2025-11-04',
                                'end': '2025-11-11'},

                                {'start': '2025-11-11',
                                'end': '2025-11-18'},

                                {'start': '2025-11-18',
                                'end': '2025-11-25'},

                                {'start': '2025-11-25',
                                'end': '2025-12-02'},

                                {'start': '2025-12-02',
                                'end': '2025-12-09'},

                                {'start': '2025-12-09',
                                'end': '2025-12-16'},

                                {'start': '2025-12-16',
                                'end': '2025-12-23'},

                                {'start': '2025-12-23',
                                'end': '2025-12-30'},

                                {'start': '2025-12-30',
                                'end': '2026-01-06'}];
